version: '3'
services:
  mysql:
    image: mysql/mysql-server:8.0.28
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
    ports:
      - 127.0.0.1:3308:3306
  mysql2:
    image: mysql/mysql-server:8.0.28
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
    ports:
      - 127.0.0.1:3309:3306
  mysql3:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      # MYSQL_ROOT_PASSWORD: mysecretpassword
      # MYSQL_DATABASE: mydatabase
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456

    ports:
      - 127.0.0.1:3305:3306

  mongodb:
    image: mongo:5.0
    ports:
      - 27018:27017
    # volumes:
    #   - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=parse
      - MONGO_INITDB_ROOT_PASSWORD=parse_pwd
  # https://hub.docker.com/_/postgres
  postgresdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456

  adminer:
    image: adminer
    restart: always
    ports:
    - 8088:8080
# mongodb ref:https://citizix.com/how-to-run-mongodb-with-docker-and-docker-compose/
 # usage: docker-compose -f mysql.yml up
 # ngrok tcp 3308

 ### 1. docker ps (get container id) => 2. docker exec -it 04314607a1d4 /bin/sh
